# Generated by Django 3.0.1 on 2019-12-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191220_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_group',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
