# Generated by Django 3.0.1 on 2019-12-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_group_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
